{% set name = "py7zr" %}
{% set version = "0.18.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dfce50712aaf77b246eaeaa46581b66a702366b43df4b53ad40d08de65c72ac3

build:
  number: 0
  noarch: python
  entry_points:
    - py7zr = py7zr.__main__:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=45.0
    - setuptools-scm >=6.0.1
  run:
    - brotli-python >=1.0.9
    - brotlicffi >=1.0.9.2
    - importlib_metadata
    - multivolumefile >=0.2.3
    - pycryptodomex >=3.6.6
    - pyppmd >=0.17.0
    - python >=3.6
    - pyzstd >=0.14.4
    - texttable
    - pybcpy
    - pybcj
    - zipfile-deflate64
    - psutil

test:
  imports:
    - py7zr
  commands:
    - py7zr --help
  requires:
    - pip

about:
  home: https://github.com/miurahr/py7zr
  summary: Pure python 7-zip library
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
